# GitHub Actions workflow for publishing the CylindiricalNearField package to PyPI
# When tag is created, this workflow will publish the package to PyPI.
# For more information on GitHub Actions, see https://docs.github.com/en/actions
name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish package
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}